### ISSUE TITLE
ARC cache is not reported as "buffers/cache"

### ISSUE THREAD

**Issue by Rainmaker52** [zfsonlinux/spl#302] opened 2013-10-26 21:03 UTC
First of all, I am not 100% sure if this is a bug, or some misinterpretation of a bug I hit.

Case in point; my system locks up when installing a Windows Virtualbox VM. This VM is installed to a "plain" ZFS filesystem, no dedup, no compression, no RAID.
Layout of the setup:
2 harddisks, 1 HDD, 1 SSD.
The HDD is configured as a ZFS pool. The SSD is partitioned. 1 partition is setup as  ZIL, the second partition is setup as L2ARC cache.
There is 1 ZVOL on the pool, configured as swap.

During the install of the VM, I see the RAM usage rise. ps does not show any significant rise in resident set size, and buffers/cache listed by "free", seems to get lower and lower.

The big problem is that the ARC cache only seems to flush when I/O is relatively low. During a installation however, the disk is pretty busy. So, at one point, the system starts swapping. When this swap is configured on the same zpool, the system just completely locks up. When the swap is configured on a separate partition, the system keeps running. However, around 200 MB of swap is then used before the ARC cache is reduced.

In my opinion the (level 1) ARC cache should be reported to the kernel as memory used for "cache/buffer", thereby letting the MM subsystem decide when data should be flushed from the cache.

**Comment by behlendorf** [comment] 2018-05-30 21:39
Closing. Working as intended.

**Closed by behlendorf** 2018-05-30 21:39 UTC
Labels: Feature
