### ISSUE TITLE
VERIFY3(c < (1ULL << 17) >> 9) failed (65535 < 256) SPLError: 18818:0:(zio.c:247:zio_buf_alloc()) SPL PANIC

### ISSUE THREAD

**Issue by akorn** [zfsonlinux/spl#390] opened 2014-09-18 15:04 UTC
Hi,

I have filesystem with xattr=sa and acltype=posixacl.

lgetxattr() on inodes with ACLs on it causes the process performing the lookup to hang, like this:

```
VERIFY3(c < (1ULL << 17) >> 9) failed (65535 < 256)
SPLError: 18818:0:(zio.c:247:zio_buf_alloc()) SPL PANIC
SPL: Showing stack for process 18818
CPU: 1 PID: 18818 Comm: rsync Tainted: P           O 3.10.16-vs2.3.6.6-superguppy #1
Hardware name: Supermicro H8SGL/H8SGL, BIOS 3.0        08/31/2012
 0000000000000000 ffff8807bed33598 ffffffff814eb2db ffff8807bed335b0
 ffffffffa019140b 0000000000000000 ffff8807bed335d0 ffffffffa019265a
 0000000000000033 ffffffffa051dae3 ffff8807bed33750 ffffffffa019be78
Call Trace:
 [<ffffffff814eb2db>] dump_stack+0x19/0x1b
 [<ffffffffa019140b>] spl_debug_dumpstack+0x46/0x49 [spl]
 [<ffffffffa019265a>] spl_debug_bug+0x88/0xcd [spl]
 [<ffffffffa019be78>] spl_PANIC+0x9d/0xc6 [spl]
 [<ffffffffa01913c3>] ? trace_unlock_tcd+0x11/0x13 [spl]
 [<ffffffffa0191f15>] ? spl_debug_msg+0x5a2/0x770 [spl]
 [<ffffffff811215d0>] ? ____cache_alloc+0x3a/0x29d
 [<ffffffff81121faa>] ? kmem_cache_alloc+0x8a/0xf8
 [<ffffffffa041721b>] ? arc_space_consume+0x9b/0xa0 [zfs]
 [<ffffffffa0417256>] ? buf_cons+0x36/0x3a [zfs]
 [<ffffffffa01964b7>] ? spl_kmem_cache_alloc+0xc6/0xb02 [spl]
 [<ffffffffa04c623c>] zio_buf_alloc+0x40/0x55 [zfs]
 [<ffffffffa0418126>] arc_get_data_buf+0x262/0x540 [zfs]
 [<ffffffffa041b9ad>] arc_buf_alloc+0x144/0x1b5 [zfs]
 [<ffffffffa041c7f3>] arc_read+0x43c/0xba7 [zfs]
 [<ffffffffa04246a9>] ? dbuf_rele_and_unlock+0x2b4/0x2b4 [zfs]
 [<ffffffffa0426546>] dbuf_read+0x58c/0x7db [zfs]
 [<ffffffffa0430b9b>] dmu_spill_hold_by_dnode+0xd4/0xfa [zfs]
 [<ffffffffa0430c32>] dmu_spill_hold_existing+0x71/0xe0 [zfs]
 [<ffffffffa0469243>] sa_get_spill+0x25/0x6d [zfs]
 [<ffffffffa046a252>] sa_attr_op+0x171/0x351 [zfs]
 [<ffffffffa046ac2a>] sa_lookup_impl+0x89/0x90 [zfs]
 [<ffffffffa046acd3>] sa_lookup+0xa2/0xb7 [zfs]
 [<ffffffffa019e1aa>] ? __cv_init+0x7b/0xd6 [spl]
 [<ffffffffa049f98d>] zfs_dirent_lock+0x3c9/0x510 [zfs]
 [<ffffffffa04a10c6>] zfs_get_xattrdir+0x68/0x152 [zfs]
 [<ffffffff8108147b>] ? should_resched+0x9/0x28
 [<ffffffff814ee800>] ? _cond_resched+0x9/0x19
 [<ffffffff814ed71f>] ? mutex_lock+0xd/0x2a
 [<ffffffffa04665f0>] ? refcount_add_many+0xdf/0xeb [zfs]
 [<ffffffffa046660d>] ? refcount_add+0x11/0x13 [zfs]
 [<ffffffffa04b33ac>] zfs_lookup+0x158/0x298 [zfs]
 [<ffffffffa04d1fb4>] __zpl_xattr_get+0xae/0x284 [zfs]
 [<ffffffffa04d2665>] zpl_xattr_get+0x57/0xc5 [zfs]
 [<ffffffffa04d3456>] zpl_get_acl+0xab/0x161 [zfs]
 [<ffffffffa04d3546>] zpl_xattr_acl_get+0x3a/0x8b [zfs]
 [<ffffffffa04d35fb>] zpl_xattr_acl_get_access+0x64/0x6f [zfs]
 [<ffffffff8114cc06>] generic_getxattr+0x47/0x59
 [<ffffffff8114cf9c>] vfs_getxattr+0x90/0x9d
 [<ffffffff8114d37e>] getxattr+0xc5/0x18e
 [<ffffffff8113b4b2>] ? final_putname+0x2f/0x32
 [<ffffffff8113b617>] ? putname+0x22/0x24
 [<ffffffff8113d987>] ? user_path_at_empty+0x84/0xad
 [<ffffffff811363e2>] ? SYSC_newlstat+0x25/0x2e
 [<ffffffff8114daba>] SyS_getxattr+0x4e/0x89
 [<ffffffff814efd56>] system_call_fastpath+0x1a/0x1f
```

The filesystem was created with 0.6.3-1~trusty from Darik's PPA ; the above was obtained with latest git master as of yesterday (zfsonlinux/spl@f9bde4f74be5e5030571415d9c869400dff3eda6, zfsonlinux/zfs@2d501583430e54be39c6aed033fc6f841e469f23)

Strace output up to the moment where the process hangs:

```
lstat("documents", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4, ...}) = 0
lgetxattr("documents", "security.selinux"
```

Additionally, listxattr() on an entry with no xattrs returns EFAULT (at least after the above panic).

**Comment by behlendorf** [comment] 2016-04-26 22:05
Closing, the root cause of the issue was resolved by zfsonlinux/zfs@4254acb05743dc2175ae76f6e15b0785d4b688fd

**Closed by behlendorf** 2016-04-26 22:05 UTC
