### ISSUE TITLE
DKMS build failure on openSUSE Tumbleweed - No rule to make target 'module/NONE'

### ISSUE THREAD

**Issue by darrenfreeman** [zfsonlinux/spl#695] opened 2018-03-26 16:03 UTC
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | openSUSE
Distribution Version    | Tumbleweed
Linux Kernel                 | 4.15.9-1-default #1 SMP PREEMPT
Architecture                 | x86-64
SPL Version                  | git, latest = commit 43983eb2024ec6b3280e6e06a6fb621ee3bb2a41

I'm trying to install zfs on a machine that's never had it before. I did a zypper dup to upgrade the whole system to the latest packages, before proceeding.

I performed: `./autogen.sh && ./configure && make pkg`

I'm not entirely sure which of the RPMs I should be installing. I think the install guide could really use an explanation of what all the different packages are for, and which are optional or mutually exclusive.

Starting from no installed packages, I performed:

`rpm -i spl-0.7.0-31_g43983eb.x86_64.rpm spl-dkms-0.7.0-31_g43983eb.noarch.rpm`

```
Loading new spl-0.7.0 DKMS files...
Building for 4.15.9-1-default
Building initial module for 4.15.9-1-default
Error! Bad return status for module build on kernel: 4.15.9-1-default (x86_64)
Consult /var/lib/dkms/spl/0.7.0/build/make.log for more information.
warning: %post(spl-dkms-0.7.0-31_g43983eb.noarch) scriptlet failed, exit status 10
```

From that log:

```
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /var/lib/dkms/spl/0.7.0/build/module/spl/spl.mod.o
  CC      /var/lib/dkms/spl/0.7.0/build/module/splat/splat.mod.o
  LD [M]  /var/lib/dkms/spl/0.7.0/build/module/spl/spl.ko
  LD [M]  /var/lib/dkms/spl/0.7.0/build/module/splat/splat.ko
make[3]: Leaving directory '/usr/src/linux-4.15.9-1-obj/x86_64/default'
make[2]: Leaving directory '/var/lib/dkms/spl/0.7.0/build/module'
make[2]: Entering directory '/var/lib/dkms/spl/0.7.0/build'
make[2]: *** No rule to make target 'module/NONE', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/var/lib/dkms/spl/0.7.0/build'
make[1]: *** [Makefile:609: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.7.0/build'
make: *** [Makefile:490: all] Error 2
```

**Comment by behlendorf** [comment] 2018-03-26 17:01
@darrenfreeman this was caused by upstream kernel bug https://bugzilla.redhat.com/show_bug.cgi?id=1550152#c6 which effectively breaks all external kernel module builds starting with the 4.15.9-1 kernel.

You're going to want to rollback to an earlier kernel until they sort this out.  The fedora developers are [rolling back this change](https://src.fedoraproject.org/rpms/kernel/c/0ff2afdbe0501525ee2d5b53fdc20a320b29bc8c?branch=master) but it'll be up to each distribution how to handle this in the short term.

**Comment by darrenfreeman** [comment] 2018-03-27 01:54
I tested with the slightly newer kernel now in Tumbleweed, 4.15.11-1-default, same result.

**Comment by darrenfreeman** [comment] 2018-03-27 04:42
There is no way to get an earlier version of the kernel with Tumbleweed, if they break it, you're stuck waiting. So I've moved to the latest from Leap 42.3. Same problem.

```
Loading new spl-0.7.0 DKMS files...
Building for 4.4.120-45-default
Building initial module for 4.4.120-45-default
Error! Bad return status for module build on kernel: 4.4.120-45-default (x86_64)
Consult /var/lib/dkms/spl/0.7.0/build/make.log for more information.
warning: %post(spl-dkms-0.7.0-31_g43983eb.noarch) scriptlet failed, exit status 10
```

And the log:

```
make[2]: Entering directory '/var/lib/dkms/spl/0.7.0/build'
make[2]: *** No rule to make target 'module/NONE', needed by 'all-am'.  Stop.
```

What should I try next? Is it possible they backported that bad fix onto 4.4.120? Or is something else wrong?

Also is there anything wrong with just using the kmod version, since that's already been compiled by `make pkg`?

**Comment by darrenfreeman** [comment] 2018-04-10 17:33
openSUSE Tumbleweed has been updated to kernel version 4.16.0-1-default . However, the dkms version of SPL still fails to build.

I installed the kmod version instead, it didn't give any warnings.

Given that an older version prior to 4.15.9-1 had the same failure, and kmod appears to have succeeded, is it really the same bug @behlendorf ?

**Comment by behlendorf** [comment] 2018-05-30 23:44
Closing.  The spl and zfs repositories have been merged. Can you try again building just zfs and if there's still an issue open a new issue on the zfs issue tracker.

**Closed by behlendorf** 2018-05-30 23:44 UTC
